import type { Import40CaseDto, Import40DeclarationDto, Import40GoodsItemDto } from '@/api/import40'

/** Товар ДТ с сервера: каждое поле заполнено своим значением. */
export const fullGoodsDto = (over: Partial<Import40GoodsItemDto> = {}): Import40GoodsItemDto => ({
  id: 'g1',
  sortOrder: 0,
  description: 'ВИНТЫ',
  tnvedCode: '7318150000',
  tnvedDescription: 'винты и болты',
  countryOfOrigin: 'CN',
  quantity: 100,
  unit: 'шт',
  unitCode: '796',
  grossWeightKg: 12.5,
  netWeightKg: 11.2,
  packagesCount: 4,
  quantityTypeCode: 'Q1',
  invoiceValue: 1500.5,
  currency: 'USD',
  procedureCode: '4000',
  previousProcedureCode: '00',
  goodsMoveFeatureCode: '000',
  tradeMarkName: 'ACME',
  productMarkName: 'MARK',
  productModelName: 'M-1',
  productArticle: 'ART-1',
  manufacturerName: 'ACME LTD',
  packageAvailabilityCode: '1',
  cargoPlacesQuantity: 3,
  packageKindCode: 'CT',
  packageQuantity: 3,
  prefClearanceCode: 'ОО',
  prefDutyCode: 'ОО',
  prefExciseCode: 'Z',
  prefVatCode: 'ОО',
  vatRatePreferential: 0.05,
  customsValueKzt: 750000,
  statisticValueUsd: 1500,
  valuationMethodCode: '1',
  quotaAmount: 7,
  prohibitionCode: 'C1700',
  ipoCode: 'I',
  payments: [{ taxModeCode: '1010', taxBase: 1, rateValue: 2, amountKzt: 3 } as never],
  needsTpinRecalc: true,
  containerNumber: 'MSKU1234567',
  tempImportMonths: 6,
  certificationNote: 'сертификат',
  oisIndicatorCode: 'N',
  restrictionMarks: 'С,М',
  oisRegNumber: '1234',
  oisCountryCode: 'KZ',
  markings: [{ number: 'KIZ-1', kizCount: 2 }],
  exciseKind: 'K1',
  antiDumpingKind: 'AD1',
  taxVolumeL: 1.5,
  taxAlcoholL: 0.4,
  taxPieces: 10,
  engineVolumeCm3: 1600,
  extras: { productionPlaceName: 'ЗАВОД', exciseStamps: [], vehicles: [], packages: [] } as never,
  ...over,
})

/** ДТ с сервера: каждое поле шапки заполнено своим значением (пустых и значений по умолчанию нет). */
export const fullDto = (over: Partial<Import40DeclarationDto> = {}): Import40DeclarationDto => ({
  id: 'dt1',
  caseId: 'case1',
  declarationNumber: '55302/091026/0000123',
  corridor: 'yellow',
  procedureCode: '40',
  sender: { name: 'SENDER CO', countryCode: 'CN', region: 'GUANGDONG', city: 'SHENZHEN', street: 'MAIN ST' },
  senderDistrict: 'S-DISTRICT',
  senderSettlement: 'S-SETTLEMENT',
  senderHouse: '1',
  senderApt: '2',
  senderShortName: 'SENDER',
  receiver: { name: 'ТОО ПОЛУЧАТЕЛЬ', countryCode: 'KZ', region: 'АЛМАТЫ', city: 'АЛМАТЫ', street: 'АБАЯ' },
  receiverDistrict: 'R-DISTRICT',
  receiverSettlement: 'R-SETTLEMENT',
  receiverHouse: '10',
  receiverApt: '20',
  receiverBin: '123456789012',
  receiverCategoryCode: '1',
  receiverKatoCode: '751110000',
  receiverShortName: 'ПОЛУЧАТЕЛЬ',
  departureCountryCode: 'CN',
  destinationCountryCode: 'KZ',
  incoterms: 'FCA',
  currency: 'USD',
  totalInvoiceValue: 1500.5,
  exchangeRate: 495.12,
  transactionNatureCode: '010',
  transactionFeatureCode: '00',
  tradeCountryCode: 'CN',
  originCountryCode: 'CN',
  incotermsPlace: 'ШЭНЬЧЖЭНЬ',
  consigneeEqualsDeclarant: true,
  financialSubjectEqualsDeclarant: true,
  goodsLocationCode: '11',
  goodsLocationRegisterNumber: '0001/123',
  goodsLocationCountryCode: 'RU',
  goodsLocationStation: 'СТАНЦИЯ',
  goodsLocationAddress: 'АДРЕС СВХ',
  goodsLocationCustomsOfficeCode: '55302',
  borderCustomsOfficeCode: '55201',
  borderCustomsOfficeName: 'ТП ХОРГОС',
  submissionCustomsOfficeCode: '55302',
  submissionDate: '2026-10-05T00:00:00Z',
  borderTransportModeCode: '31',
  borderTransportNationality: 'CN',
  borderTransportNumbers: [{ number: 'A123BC', role: 'head' } as never],
  arrivalTransportModeCode: '30',
  arrivalTransportNationality: 'RU',
  arrivalTransportNumbers: [{ number: 'B456DE' } as never],
  rateType: 'WTO',
  splitRole: 'vto',
  isSplitReplaced: false,
  updatedAtUtc: '2026-10-09T10:11:12.123456Z',
  factPayments: [{ sortOrder: 0, taxModeCode: '1010', amount: 20000, exchangeRate: 1, paymentDocDate: '2026-10-05', payerTaxpayerId: '123', paymentDate: '2026-10-05', paymentMethodCode: 'БН' }],
  declarationTypeCode: 'ЭК',
  declarationFeatureCode: 'ЭД',
  sheetNumber: 1,
  totalSheets: 2,
  shippingSpecSheets: 3,
  referenceNumber: 'REF-1',
  financialSubjectName: 'ФИНЛИЦО',
  financialSubjectBin: '210987654321',
  financialSubjectCountryCode: 'KZ',
  financialSubjectRegion: 'F-REGION',
  financialSubjectCity: 'F-CITY',
  financialSubjectStreet: 'F-STREET',
  financialSubjectDistrict: 'F-DISTRICT',
  financialSubjectSettlement: 'F-SETTLEMENT',
  financialSubjectHouse: '3',
  financialSubjectApt: '4',
  financialSubjectCategoryCode: '2',
  financialSubjectKatoCode: '751110001',
  financialSubjectShortName: 'ФИН',
  declarantName: 'ТОО ДЕКЛАРАНТ',
  declarantBin: '111111111111',
  declarantCountryCode: 'KZ',
  declarantRegion: 'D-REGION',
  declarantCity: 'D-CITY',
  declarantStreet: 'D-STREET',
  declarantDistrict: 'D-DISTRICT',
  declarantSettlement: 'D-SETTLEMENT',
  declarantHouse: '5',
  declarantApt: '6',
  declarantCategoryCode: '3',
  declarantKatoCode: '751110002',
  declarantShortName: 'ДЕКЛ',
  containerIndicator: true,
  inlandTransportModeCode: '30',
  deferralDocType: '09011',
  deferralNumber: 'DEF-1',
  deferralDate: '2026-10-01',
  deferralDueDate: '2026-11-01',
  guaranteeInvalidFor: 'RU',
  signatoryFullName: 'ИВАНОВ И.И.',
  signatoryPosition: 'СПЕЦИАЛИСТ',
  signatoryDocument: 'ПАСПОРТ',
  signatoryDocTypeCode: 'RU01001',
  signatoryDocNumber: 'N123',
  signatoryDocIssueDate: '2020-01-01',
  signatoryDocIssuedBy: 'МВД',
  signatoryDocCountryCode: 'KZ',
  powerOfAttorney: 'ДОВ-1',
  powerOfAttorneyDate: '2026-01-01',
  powerOfAttorneyValidUntil: '2026-12-31',
  brokerContractNumber: 'ДОГ-1',
  signatoryPhone: '+77001234567',
  signedDate: '2026-10-05',
  dtsFreeOfCharge: true,
  dtsPlaceName: 'АЛМАТЫ',
  dtsRelation: true,
  dtsRelationPriceInfluence: true,
  dtsRelationApproxValue: true,
  dtsRestriction: true,
  dtsValueCondition: true,
  dtsRoyaltyContract: true,
  dtsRoyaltyFee: true,
  dtsSubsequentResale: true,
  dtsMethodReason: 'ПРИЧИНА',
  totalGoodsCount: 1,
  totalPackagesCount: 3,
  totalCustomsValue: 750000,
  goodsItems: [fullGoodsDto()],
  doc44Items: [{
    id: 'd1', sortOrder: 0, docTypeCode: '04021', docTypeName: 'ИНВОЙС', docNumber: 'INV-1', docDate: '2026-09-01',
    goodsItemIndex: 0, appliesToAll: true, goodsItemIndexes: '1,2', docStartDate: '2026-09-01', docValidityDate: '2027-09-01',
    issueCountryCode: 'CN',
  }],
  prevDocItems: [{ id: 'p1', docTypeCode: '09013', docNumber: 'PREV-1', docDate: '2026-09-02', goodsNumber: '1', goodsItemIndex: 0, sortOrder: 0 }],
  expenses: [{ sortOrder: 0, expenseTypeCode: '17', amount: 300, currencyCode: 'USD' }],
  ...over,
})

export const caseDto = (over: Partial<Import40CaseDto> = {}): Import40CaseDto => ({
  id: 'case1',
  number: 'И-1',
  clientId: 'client1',
  clientName: 'КЛИЕНТ',
  cargo: 'ВИНТЫ',
  status: 2,
  assignedDeclarantId: null,
  declarations: [fullDto()],
  ...over,
}) as Import40CaseDto
